django_sem1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('oneapp.urls', namespace='oneapp')),
    path('twoapp/', include('twoapp.urls', namespace='twoapp')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

oneapp/urls.py
from django.contrib import admin
from django.urls import path

from oneapp.views import IndexView, Contact

app_name = 'oneapp'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('contact/', Contact.as_view(), name='contact'),
]

twoapp/urls.py
from django.urls import path, include

from twoapp.views import GalerieView, ListOrderView, ProductsView

app_name = 'twoapp'

urlpatterns = [
    path('', GalerieView.as_view(), name='galerie'),
    path('orders/', ListOrderView.as_view(), name='list_order'),
    path('products/', ProductsView.as_view(), name='products'),
]

twoapp/models.py
from django.db import models

# Create your models here.

class Client(models.Model):
    name = models.CharField(max_length=100)
    phone_number = models.CharField(max_length=100, null=True, blank=True)
    address = models.TextField(null=True, blank=True)
    date_registration = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    qwontity = models.IntegerField()
    date_registration = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='images/', null=True, blank=True)

    def __str__(self):
        return self.name

class Order(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    total_price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    products = models.ManyToManyField(Product, related_name='orders')
    date_registration = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        # Переместите этот импорт вверх, если он еще не произошел
        from django.db.models import Sum

        # Обновим total_price только если объект Order уже имеет первичный ключ
        if self.pk:
            products_total_price = self.products.aggregate(Sum('price'))['price__sum']
            self.total_price = products_total_price if products_total_price else 0

        super().save(*args, **kwargs)


    def __str__(self):
        return str(self.id)

twoapp/forms.py
from django import forms

from twoapp.models import Client, Product


class ClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ['name', 'phone_number', 'address']


class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = ['name', 'description', 'price', 'qwontity', 'image']

twoapp/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, HttpResponse, reverse
from django.views import View

from twoapp.forms import ClientForm, ProductForm
from twoapp.models import Order, Client
from datetime import timedelta
from django.utils import timezone

# Create your views here.
class GalerieView(View):
    def get(self, request):
        form = ClientForm()
        context = {
            'form': form,
            'title': 'Галерея',
        }
        return render(request, 'twoapp/index.html', context=context)

    def post(self, request):
        form = ClientForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('twoapp:galerie'))


class ListOrderView(View):
    def get(self, request):
        days = request.GET.get('days', None)
        if days is None:
            orders = Order.objects.all()
        else:
            end_date = timezone.now()
            start_date = end_date - timedelta(days=int(days))
            orders = Order.objects.filter(date_registration__range=[start_date, end_date])
        context = {
            'title': 'Список заказов',
            'orders': orders,
        }
        return render(request, 'twoapp/list_order.html', context=context)


class ProductsView(View):
    def get(self, request):
        form = ProductForm()
        context = {
            'title': 'Список продуктов',
            'form': form,
        }
        return render(request, 'twoapp/products.html', context=context)

    def post(self, request):
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('twoapp:products'))

twoapp/templates/twoapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
</head>
<body>
    <form action="{% url 'twoapp:galerie' %}" method="post">
        {% csrf_token %}
        {{ form.as_ul }}

        <!-- Кнопка подтверждения -->
        <button type="submit">Подтвердить</button>
    </form>
</body>
</html>

twoapp/templates/twoapp/list_order.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
</head>
<body>
    <form method="get" action="{% url 'twoapp:list_order' %}">
        <button type="submit" name="days" value="7">Last 7 days</button>
        <button type="submit" name="days" value="30">Last 30 days</button>
        <button type="submit" name="days" value="365">Last 365 days</button>
    </form>

    {% for item in orders %}
        <p>{{ item.client.name }}</p>
        <p>{{ item.date_registration }}</p>
        {% for product in item.products.all %}
            <p>{{ product.name }}</p>
            <p>{{ product.price }}</p>
            {% if product.image %}
                <img src="{{ product.image.url }}" alt="{{ product.name }}">
            {% endif %}
        {% endfor %}
    {% endfor %}
</body>
</html>

twoapp/templates/twoapp/products.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
</head>
<body>
    <form action="{% url 'twoapp:products' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_ul }}

        <!-- Кнопка подтверждения -->
        <button type="submit">Подтвердить</button>
    </form>
</body>
</html>